name: setup-node
description: 'Setup Node.js âš™ï¸ - Install pnpm ðŸ”§ - Install dependencies ðŸ”§'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      name: Install Node.js âš™ï¸
      with:
        node-version: 20

    - uses: pnpm/action-setup@v4
      name: Install pnpm ðŸ”§
      with:
        version: 8
        run_install: false

    - name: Expose pnpm config(s) through "$GITHUB_OUTPUT"
      id: pnpm-config
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Cache rotation keys
      id: cache-rotation
      shell: bash
      run: |
        echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

    - name: Install dependencies ðŸ”§
      run: pnpm install
      shell: bash
