version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: mail_server
    restart: always
    logging:
      driver: 'none'
    ports:
      - '1025:1025' # smtp
      - '8025:8025' # web ui

volumes:
  redis_data:
