/**
 * GENERATED by scripts/gen-palettes.mjs. Do not edit by hand.
 *
 * Mirrors the palette table that produced src/styles/palettes.css, so the
 * picker cannot offer a palette the stylesheet has no block for.
 */

export const PALETTES = [
  { id: 'teal', name: 'Teal' },
  { id: 'sakura', name: 'Sakura' },
  { id: 'ai', name: 'Ai' },
  { id: 'kohaku', name: 'Kohaku' },
  { id: 'fuji', name: 'Fuji' },
  { id: 'sumi', name: 'Sumi' },
] as const

export type PaletteId = (typeof PALETTES)[number]['id']

export const DEFAULT_PALETTE: PaletteId = 'teal'
