name: TypeScript check
on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/actions/setup-node

      - name: TypeScript check
        run: pnpm run typecheck
        env:
          NEXT_PUBLIC_PUBLIC_URL: ${{ secrets.NEXT_PUBLIC_PUBLIC_URL }}
          NEXT_PUBLIC_WRITEWIZ_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WRITEWIZ_PROJECT_ID }}
          NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${{ secrets.NEXT_PUBLIC_TURNSTILE_SITE_KEY }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_MAIL_TO: ${{ secrets.RESEND_MAIL_TO }}
